obj-$(CONFIG_QCOM_GSBI)	+=	qcom_gsbi.o
obj-$(CONFIG_QCOM_PM)	+=	spm.o
obj-$(CONFIG_QCOM_SMD) +=	smd.o
obj-$(CONFIG_QCOM_SMD_RPM)	+= smd-rpm.o
obj-$(CONFIG_MSM_SMEM)	+=	smem.o smem_debug.o
obj-$(CONFIG_QCOM_PROC_COMM) +=	proc_comm.o
